apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-study-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: pongpong.io
    http:
      paths:
      - backend:
          serviceName: k8s-frontend
          servicePort: 3000
  - host: www.pongpong.io
    http:
      paths:
      - backend:
          serviceName: k8s-frontend
          servicePort: 3000
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: k8s-frontend
  template:
    metadata:
      labels:
        type: frontend
        service: k8s-frontend
    spec:
      containers:
      - name: k8s-frontend
        image: subicura/k8s-frontend

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend
spec:
  ports:
  - port: 3000
  selector:
    type: frontend
    service: k8s-frontend
